linters:
    enable-all: true
    disable:
        - maligned
        - dupl

linters-settings:
    golint:
        min-confidence: 0.1

    goimports:
        local-prefixes: github.com/sagikazarmark/viper-vault
