version: "3.7"

services:
    vault:
        image: vault:1.1.2
        command: server -dev
        cap_add:
            - IPC_LOCK
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: root
            VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
