name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.13', '1.14', '1.15']
    env:
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org
      PLZ_ARGS: -p

    services:
      vault:
        image: vault:1.5.3
        ports:
          - 8200
        env:
          SKIP_SETCAP: true
          VAULT_DEV_ROOT_TOKEN_ID: root

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set Please overrides
        run: echo "::set-env name=PLZ_OVERRIDES::build.path:$PATH"

      - name: Checkout code
        uses: actions/checkout@v2

      # Disabled until experimental features are finalized
      # - name: Build
      #   run: ./pleasew $PLZ_ARGS build //...

      - name: Test
        run: |
          # Disabled until experimental features are finalized
          # ./pleasew $PLZ_ARGS test //...
          ./pleasew $PLZ_ARGS gotest
        env:
          VAULT_ADDR: http://0.0.0.0:${{ job.services.vault.ports['8200'] }}
          VAULT_TOKEN: root

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: plz-out/log/coverage.txt

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org
      PLZ_ARGS: -p

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Set Please overrides
        run: echo "::set-env name=PLZ_OVERRIDES::build.path:$PATH"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        run: ./pleasew $PLZ_ARGS lint

  experimental:
    name: Build (Please experimental)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.15']
    env:
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org
      PLZ_ARGS: -p --profile experimental

    services:
      vault:
        image: vault:1.5.3
        ports:
          - 8200
        env:
          SKIP_SETCAP: true
          VAULT_DEV_ROOT_TOKEN_ID: root

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set Please overrides
        run: echo "::set-env name=PLZ_OVERRIDES::build.path:$PATH"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./pleasew $PLZ_ARGS build ./...

      - name: Test
        run: ./pleasew $PLZ_ARGS test ./...
        env:
          VAULT_ADDR: http://0.0.0.0:${{ job.services.vault.ports['8200'] }}
          VAULT_TOKEN: root

      - name: Save Please log output
        uses: actions/upload-artifact@v1
        with:
          name: build-log
          path: plz-out/log

      # TODO: upload coverage
